package gremlin

const (
	// StatusSuccess ...
	StatusSuccess = 200
	// StatusNoContent ...
	StatusNoContent = 204
	// StatusPartialContent ...
	StatusPartialContent = 206
	// StatusUnauthorized ...
	StatusUnauthorized = 401
	// StatusAuthenticate ...
	StatusAuthenticate = 407
	// StatusMalformedRequest ...
	StatusMalformedRequest = 498
	// StatusInvalidRequestArguments ...
	StatusInvalidRequestArguments = 499
	// StatusServerError ...
	StatusServerError = 500
	// StatusScriptEvaluationError ...
	StatusScriptEvaluationError = 597
	// StatusServerTimeout ...
	StatusServerTimeout = 598
	// StatusServerSerializationError ...
	StatusServerSerializationError = 599
)

// ErrorMsg ...
var ErrorMsg = map[int]string{
	StatusUnauthorized:             "Unauthorized",
	StatusAuthenticate:             "Authenticate",
	StatusMalformedRequest:         "Malformed Request",
	StatusInvalidRequestArguments:  "Invalid Request Arguments",
	StatusServerError:              "Server Error",
	StatusScriptEvaluationError:    "Script Evaluation Error",
	StatusServerTimeout:            "Server Timeout",
	StatusServerSerializationError: "Server Serialization Error",
}
