version: 2
jobs:
  build:
    working_directory: /go/src/github.com/miseyu/go-gremlin
    docker:
      - image: circleci/golang:1.12.0
  environment:
    TZ: Asia/Tokyo
    GO111MODULE: "on"
  steps:
    - checkout
    - restore_cache:
        name: Restore go modules cache
        keys:
          - v1-mod-{{ .Branch }}-{{ checksum "go/go.mod" }}
    - run:
        name: Vendoring
        command: go mod download
    - save_cache:
      name: Save go modules cache
      key: v1-mod-{{ .Branch }}-{{ checksum "go/go.mod" }}
      paths:
        - ~/go/pkg/mod/cache
    - run: go get ./...
    - run: go test -v ./...

workflows:
  version: 2
  build:
    jobs:
      - build